name: flutter_myopia_ai
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  fluttertoast: #^3.0.4
  flutter_svg: #^0.13.0+2
  flustars: #^0.2.6+1
  simple_gesture_detector: #^0.1.3
  tuple: #^1.0.1
  date_utils: #^0.1.0
  charts_flutter:
    path: ./charts_flutter
  sqflite: #^1.1.6+3
  flutter_seekbar:
    git: https://github.com/LiuC520/flutter_seekbar.git
  audioplayers: #^0.13.1
  url_launcher: #^5.1.2
  package_info: #0.4.0+6

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family:  MyIcons
      fonts:
        - asset: fonts/MyFlutterApp.ttf
  assets:
    - assets/ic_glasses.svg
    - assets/ic_assignment.svg
    - assets/ic_search_myopia_level.svg
    - assets/ic_statistic.svg
    - assets/ic_20_20_20.svg
    - assets/ic_feedback.svg
    - assets/ic_about_us.svg
    - assets/ic_rate_us.svg
    - assets/ic_reading.svg
    - assets/ic_computer.svg
    - assets/ic_watching_tv.svg
    - assets/ic_phone.svg
    - assets/ic_game.svg
    - assets/ic_others.svg
    - assets/ic_bike.svg
    - assets/ic_hike.svg
    - assets/ic_run.svg
    - assets/ic_sports.svg
    - assets/ic_swim.svg
    - assets/ic_others_outdoor.svg
    - assets/background_reading.svg
    - assets/background_computer.svg
    - assets/background_phone.svg
    - assets/background_watching_tv.svg
    - assets/background_game.svg
    - assets/background_others.svg
    - assets/background_swim.svg
    - assets/background_sports.svg
    - assets/background_run.svg
    - assets/background_bike.svg
    - assets/background_hike.svg
    - assets/background_others_outdoor.svg
    - assets/eye_exercise_1.svg
    - assets/eye_exercise_2.svg
    - assets/eye_exercise_3.svg
    - assets/eye_exercise_4.svg
    - assets/ic_logo.svg
    - assets/about_us_lei.svg
    - assets/about_us_meng.svg
    - assets/ic_home_left_top_eye.svg
    - assets/ic_home_right_bottom_people.svg
    - assets/ic_home_left_top_smile.svg
    - assets/ic_home_right_bottom_exercise_people.svg
    - images/img_20_20_20.png
    - images/2.0x/img_20_20_20.png
    - images/3.0x/img_20_20_20.png
    - images/eye_exercise_face_1.png
    - images/2.0x/eye_exercise_face_1.png
    - images/3.0x/eye_exercise_face_1.png
    - images/eye_exercise_face_2.png
    - images/2.0x/eye_exercise_face_2.png
    - images/3.0x/eye_exercise_face_2.png
    - images/top_man_pic.jpeg
    - images/developer_pic.jpeg
    - assets/eye_exercise_music.mp3
    - assets/eye_exercise_music_en.mp3
    - assets/light_warning.mp3
    - assets/20_warning.mp3
    - assets/target_times_up.mp3
