/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';

  static const IconData ic_data_empty_state = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData ic_pie_chart = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData ic_activity = const IconData(0xe81d, fontFamily: _kFontFam);
}
